---
title: |
  ?aayaaqa (Herring) Spawn Dynamics
author: |
  Landmark Fisheries Research BCSRIF2-3\
  Working Paper for Uu-a-thluk Fisheries


address: |
  ^1^Landmark Fisheries Research\
     213-2414 St Johns Street\
     Port Moody, British Columbia, V3H 2B1, Canada\


date: "March 2026"
geometry: letterpaper
toc: true
fontsize: 12pt
lineno: false #line number
draft: true # double spacing on
csl-refs: true
numbersections: true
link-citations: true
bibliography: bib/library.bib

# Any extra LaTeX code for the header:
header-includes:
  - \usepackage{color}
  - \usepackage{colortbl}
  - \usepackage{multirow}
  - \usepackage{lscape}
  - \usepackage{pdflscape}
  - \usepackage{longtable}
  - \usepackage{bbold}
  - \usepackage{float}
  - \usepackage{tikz}
  - \usepackage{cmbright}
  - \usepackage{mathrsfs}
  - \usepackage{amsmath}
  - \usepackage{amssymb}
  - \usepackage{pxfonts}
  - \DeclareMathOperator{\logit}{logit}
  - \newcommand{\blandscape}{\begin{landscape}}
  - \newcommand{\elandscape}{\end{landscape}}
  - \DeclareMathOperator*{\argmax}{arg\,max}
  - \DeclareMathOperator*{\argmin}{arg\,min}
  - \usepackage[titletoc, title]{appendix}
---

```{r setup, echo=FALSE, cache=FALSE, message=FALSE, results='hide', warning=FALSE}
library(knitr)
if (is_latex_output()) {
  knitr_figs_dir <- "knitr-figs-pdf/"
  knitr_cache_dir <- "knitr-cache-pdf/"
  fig_out_type <- "pdf"
  kable_format <- "latex"
} else {
  knitr_figs_dir <- "knitr-figs-docx/"
  knitr_cache_dir <- "knitr-cache-docx/"
  fig_out_type <- "png"
  kable_format <- "pandoc"
  options(knitr.table.format = "pandoc")
}
fig_asp <- 0.618
fig_width <- 9
fig_out_width <- "6in"
fig_dpi <- 180
fig_align <- "center"
fig_pos <- "H"
opts_chunk$set(
  collapse = TRUE,
  warning = FALSE,
  message = FALSE,
  comment = "#>",
  fig.path = knitr_figs_dir,
  cache.path = knitr_cache_dir,
  fig.asp = fig_asp,
  fig.width = fig_width,
  out.width = fig_out_width,
  echo = FALSE,
  cache.comments = FALSE,
  dev = fig_out_type,
  dpi = fig_dpi,
  fig.align = fig_align,
  fig.pos = fig_pos
)
```

```{r loadStuff, echo = FALSE, include = FALSE, message = FALSE }

# packages
library(dplyr)
library(readr)
library(tibble)
library(kableExtra)
library(bookdown)
library(knitr)
library(tidyverse)
library(here)
library(RColorBrewer)
library(scales)
library(stringr)
library(zoo)

# Source utility scripts (DDM and predM repo versions)
source(here('R/DDM/ms3Rtools.R'))
source(here('R/DDM/ms3RrefPts.R'))
source(here('R/DDM/ms3Rplots.R'))
source(here('R/predM/ms3Rtools.R'))
source(here('R/predM/ms3RrefPts.R'))
source(here('R/predM/ms3Rplots.R'))
source(here('R/ms3Rstats.R'))

# Source figure/table wrapper scripts
source(here('R/plotMethods.R'))
source(here('R/plotResults.R'))
source(here('R/tableMaker.R'))

# Load OM history fits
DDMfit <- readRDS(here(
  'Models/OMHistory/fit_WCVI2023_OM_mle/fit_WCVI2023_OM_mle.rds'))
load(here('Models/OMHistory/fit_1S_2024/fit_1S_2024.RData'))
fit1S <- reports; rm(reports)
load(here('Models/OMHistory/fit_3S_2024/fit_3S_2024.RData'))
fit3S <- reports; rm(reports)

# Load simulation results (each .RData loads a 'blob'; rename immediately)
load(here(paste0(
  'Models/Sims/sim_DDM_OM-SISCA_DIM_minE0847_MP/',
  'sim_DDM_OM-SISCA_DIM_minE0847_MP.RData')))
simDDM <- blob

load(here(paste0(
  'Models/Sims/sim_1SpredMOM_minEMP_full/',
  'sim_1SpredMOM_minEMP_full.RData')))
sim1S <- blob

load(here(paste0(
  'Models/Sims/3S_allocTest/',
  'sim_parBattestAlloc-3S_predM_OM-1S_DIM_MP1/',
  'sim_parBattestAlloc-3S_predM_OM-1S_DIM_MP1.RData')))
sim3S_MP1 <- blob

load(here(paste0(
  'Models/Sims/3S_allocTest/',
  'sim_parBattestAlloc-3S_predM_OM-1S_DIM_MP2/',
  'sim_parBattestAlloc-3S_predM_OM-1S_DIM_MP2.RData')))
sim3S_MP2 <- blob

load(here(paste0(
  'Models/Sims/3S_allocTest/',
  'sim_parBattestAlloc-3S_predM_OM-1S_DIM_MP3/',
  'sim_parBattestAlloc-3S_predM_OM-1S_DIM_MP3.RData')))
sim3S_MP3 <- blob
rm(blob)

# Patch missing om fields on single-stock blobs so ms3Rplots.R
# utility functions can find fYear, stockNames_sp, areaNames, etc.
.patchBlob <- function(obj) {
  ctl      <- obj$ctlList$opMod
  nS       <- obj$om$nS
  nP       <- obj$om$nP
  # Area names from histRpt index dimnames
  areaLabs <- dimnames(ctl$histRpt$I_pgt)[[1]]
  if (is.null(obj$om$fYear) || length(obj$om$fYear) == 0)
    obj$om$fYear <- ctl$fYear
  if (is.null(obj$om$speciesNames) ||
      length(obj$om$speciesNames) == 0)
    obj$om$speciesNames <- c("Herring", rep("", nS - 1))
  if (is.null(obj$om$areaNames) ||
      length(obj$om$areaNames) == 0)
    obj$om$areaNames <- areaLabs
  if (is.null(obj$om$stockNames_sp) ||
      length(obj$om$stockNames_sp) == 0) {
    sn <- matrix("", nrow = nS, ncol = nP)
    sn[1, ] <- areaLabs
    obj$om$stockNames_sp <- sn
  }
  if (is.null(obj$om$fleetNames) ||
      length(obj$om$fleetNames) == 0)
    obj$om$fleetNames <- ctl$fleets
  if (is.null(obj$om$yrs) || length(obj$om$yrs) == 0)
    obj$om$yrs <- seq(
      from       = ctl$fYear,
      by         = 1,
      length.out = obj$om$nT)
  obj
}
simDDM    <- .patchBlob(simDDM)
sim1S     <- .patchBlob(sim1S)
sim3S_MP1 <- .patchBlob(sim3S_MP1)
sim3S_MP2 <- .patchBlob(sim3S_MP2)
sim3S_MP3 <- .patchBlob(sim3S_MP3)

```
